#!/bin/bash
# 
# repos / apps for ubuntu
#

echo
echo '----------------its ONNNNNNNNNNN!!---------------'
echo

#restricted g00dies
sudo apt-get install ubuntu-restricted-extras
#tv-maxe repo
sudo add-apt-repository ppa:venerix/blug
#wine repo
sudo add-apt-repository ppa:ubuntu-wine/ppa
#simple lightdm manager repo
sudo apt-add-repository ppa:claudiocn/slm

#fetch themmmmmmmm
sudo apt-get update

#gnome classic , choose lightdm
sudo apt-get install gnome-session-fallback

#xubuntu-desktop
sudo apt-get install xubuntu-desktop

#school-related
sudo apt-get install python python-tk python3 python3-tk python-scapy wireshark eclipse git-core git-gui git-doc
#scapy updates 
sudo apt-get install tcpdump graphviz imagemagick python-gnuplot python-crypto python-pyx

#my ish 
sudo apt-get install nmap arp-scan traceroute putty ettercap-gtk gstm curl
sudo apt-get install tilda gparted usb-creator-gtk virtualbox acpi slurm screen lynx

#entertaiment
sudo apt-get install tv-maxe vlc banshee pidgin
sudo apt-get install wine 

#customization
sudo apt-get install simple-lightdm-manager

wget http://www.teamviewer.com/download/teamviewer_linux.deb
sudo dpkg -i teamviewer_linux.deb
wget http://www.skype.com/intl/en/get-skype/on-your-computer/linux/downloading.ubuntu32
sudo dpkg -i getskype-linux-beta-ubuntu-32

#upgradinggg
sudo apt-get update
sudo apt-get upgrade

echo
echo "-----------all d0ne------------"
echo "--------------------bossssssssss"
echo